apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: office-frontend
  template:
    metadata:
      labels:
        app: office-frontend
    spec:
      containers:
        - name: office-frontend
          image: neorevn/office-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: office-frontend
spec:
  type: LoadBalancer
  selector:
    app: office-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080